#!/usr/bin/env bash

geoip_update(){
    cd ${GEOIP_DIR}/nftables-geoip

    local opts=()
    if [[ -n "${GEOIP_COUNTRIES}" ]]; then
        opts+=(-c "${GEOIP_COUNTRIES}")
    fi
    opts+=(--output-dir "${GEOIP_DIR}")
    
    python3 ${GEOIP_DIR}/nftables-geoip/nft_geoip.py \
        --download \
        "${opts[@]}"

    check_root nft -f /etc/nftables.conf
    discord_send "GeoIPs have been updated."
}

geoip_manager(){
    case "${1}" in
        "update")
            geoip_update
            ;;
        *) log E "예시 : ${NAME} geoip update" ;;
    esac
}