#!/usr/bin/env bash

tailog_manager(){
    if [[ ! -z "${1}" ]]; then
        target="TAILOG_${1^^}_LOGS[@]"
        target_regex="TAILOG_${1^^}_RES[@]"
        if [[ -z "${!target}" ]]; then
            echo -e "No logfile..."
        else
            if [[ -z "${!target_regex}" ]]; then
                tail -Fqn ${TAILOG_LINES} "${!target}"
            else
                tail -Fqn ${TAILOG_LINES} "${!target}" | sed --unbuffered -r "${!target_regex}"
            fi
        fi
    fi
}
e