#!/usr/bin/env bash

CMD_DOCKER=$(which docker)
COMPOSE_ARGS=()

get_compose_files() {
    COMPOSE_FILES=()
    for file in *.yaml *.yml; do
        if [[ -f "${file}" ]]; then
            echo "${file} found..."
            COMPOSE_FILES+=("${file}")
        fi
    done
}

docker_manager(){
    case "${1}" in
        "compose")
            shift 1
            get_compose_files
            if [[ ${#COMPOSE_FILES[@]} -eq 0 ]]; then
                echo "현재 디렉토리에서 Compose 파일(.yml 또는 .yaml)을 찾을 수 업습니다."
                exit 1
            fi
            COMPOSE_ARGS=()
            for file in "${COMPOSE_FILES[@]}"; do
                COMPOSE_ARGS+=(-f ${file})
            done
            echo "   ${CMD_DOCKER} compose ${COMPOSE_ARGS[*]} ${*}"
            ${CMD_DOCKER} compose "${COMPOSE_ARGS[@]}" ${@}
            ;;
        *)
            $CMD_DOCKER ${@}
            ;;
    esac
}
