#!/usr/bin/env bash

traffic_this_month(){
    result=$(vnstat -m 1 | sed -r -n "s#^[ \t]*##p")
    this_month=$(echo "${result}" | sed -r -n "s/(20[0-9]{2}-[0-9]{2}) +([0-9]{1,3}\.[0-9]{2} [a-zA-Z]+) \| +([0-9]{1,3}\.[0-9]{2} [a-zA-Z]+) \|.+/\1 | rx: \2 \| tx: \3/p")
    echo -e "${this_month}"
}