#!/usr/bin/env bash

geoip_update(){
    cd ${GEOIP_DIR}
    python3 ${GEOIP_DIR}/nftables-geoip/nft_geoip.py \
        --download \
        --output-dir /home/ubuntu/geoip/ \
        --file-location ${GEOIP_DIR}/nftables-geoip/location.csv

    check_root cp ${GEOIP_DIR}/geoip-*.nft /etc/nftables-geoip/
    check_root systemctl reload nftables
    discord_send "GeoIPs have been updated."
}

geoip_manager(){
    case "${1}" in
        "update")
            geoip_update
            ;;
        *) log E "예시 : ${NAME} geoip [mods|update]" ;;
    esac
}