#!/usr/bin/env bash

discord_send(){
    local payload

    case "${1}" in
        "-j")
            shift 1
            payload="${1}"
            ;;
        "-n")
            shift 1
            payload="{\"username\": \"${1}\", \"content\":\"${2}\"}"
            ;;
        *)
            payload="{\"username\": \"${NAME}@$(hostname)\", \"content\":\"${1}\"}"
            ;;
    esac

    curl -X POST "${DISCORD_WEBHOOK}" \
         -H "Content-Type: application/json" \
         -d "${payload}"
}
