#!/usr/bin/env bash

tailog_manager(){
    local targets=("${@}")
    local target_logs=()
    local target_res=()

    if [[ ${#targets[@]} -lt 1 ]]; then
        targets=("DEFAULT")
    fi

    for target in "${targets[@]}"; do
        local name="TAILOG_${target^^}_LOGS[@]"
        local res="TAILOG_${target^^}_RES[@]"
        if [[ -n "${!name}" ]]; then
            target_logs+=("${!name}")
            if [[ -n "${!res}" ]]; then
                target_res+=("${!res}")
            fi
        else
            echo -e "No log file...: ${target}"
        fi
    done

    if [[ ${#target_logs[@]} -gt 0 ]]; then
        if [[ ${#target_res[@]} -gt 0 ]]; then
            tail -Fqn "${TAILOG_LINES}" ${target_logs[@]} | sed --unbuffered -r "${target_res[@]}"
        else
            tail -Fqn "${TAILOG_LINES}" ${target_logs[@]}
        fi
    else
        echo -e "No logs to tail..."
    fi
}
